main: compile
compile:
	cd sequential && make
	cd ring && make
	cd 2d && make
#	cd scripts && make
clean: 
	cd sequential && make clean
	cd ring && make clean
	cd 2d && make clean
install:
	cd scripts && make install
