main: clean  
#	gcc -Wall sw_test.c  -o sw_test
#	gcc -Wall sw_sequential.c  -o sw_sequential
#	gcc -Wall sw_simple.c  -o sw_simple
#	gcc -Wall sw_basic.c  -o sw_basic
#	gcc -Wall sw_small.c  -o sw_small
	gcc -Wall smithWaterman.c  -o smithWaterman
clean:
	/bin/rm -f sw_test sw_sequential sw_simple
	/bin/rm -f sw_basic sw_small smithWaterman
