main:
install:
	echo "do Make"
	install -v -m 755 sw_ring_random_all.sh /home/kenglish/sw
	install -v -m 755 sw_sequential_random.sh  /home/kenglish/sw
	install -v -m 755 sw_sequential_random.sh  /home/kenglish/sw
