main: clean timediff
	gcc -Wall lgsearch1.c  ../lib/mystery_function_800.o ../lib/timediff.o  -lm -o ~/bin/lgsearch1.exe 
clean:
	/bin/rm -f ~/bin/lgsearch.exe  ../lib/timediff.o
timediff:
	gcc -c ../lib/timediff.c  -o ../lib/timediff.o
